### ISSUE TITLE
Critter Collection

### ISSUE THREAD

**Issue by logonoff** [andybeargen/read#15]
As Amy, Boyan or David, I would like a page that clearly displays all my Critters so that I can navigate to them easily.

## Tasks
- [ ] Design the front end page that displays all of the user's found critters, as well as not yet found critters' silhouette
- [ ] Design a page that shows a critter's summary, shown when the user clicks on a critter
- [ ] Use back end routes to fetch all of the critters the user has found

## Acceptance criteria

- The critter collection shows all available critters, with critters that the user has not found yet only showing their silhouette
- Pressing on a critter opens up a screen showing a description of the critter and an enlarged image of the critter
