### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by giann22** [andybeargen/read#16]
As Amy, Boyan or David, I would like a library page that clearly displays all my books so that I can navigate to them easily.

## Tasks
- [ ] Design the front end page for the library that shows all your books
- [ ] Design the front end reading experience, once a user clicks on a book, they should be able to read through the book
- [ ] Use back end routes to fetch the books that a user has

## Acceptance criteria

- The library page displays all of the books that the user has uploaded
- Clicking on a book allows the user to read the pages of the book
