### ISSUE TITLE
PWA Integration

### ISSUE THREAD

**Issue by logonoff** [andybeargen/read#5]
As Amy, Boyan or David, I would like to add the Lit Critters application to my phone’s home screen so that I can easily access it.

## Tasks
- [ ] Add offline support and cache so that the app can be opened without internet. Offline app should only show user's cached critters, but not allow reading as progress cannot be tracked
- [ ] Create and register a service worker to allow for background processes and push notifications
- [ ] Add option in the dashboard for a user to add the app to their home screen

## Acceptance criteria

- Users can add the app to their phone home screen
- Users can open the app from their home screen and see the site just as they would in a browser
