### ISSUE TITLE
authenticated routes

### ISSUE THREAD

**Issue by logonoff** [andybeargen/read#65]
as amy, boyan, or david, i want to know whether or not I am logged in by being redirected to the login page when I am logged out.

## Tasks
- [x] Refactor current session system to be easier to work with later on
- [x] Add redirects to login page, and redirect login page to dashboard to prevent conflicting sessions

## Acceptance criteria
- [x] When an unauthenticated user views an authenticated route, they are shown the login page
